CREATE TABLE DimFecha
(
	FechaKey INT PRIMARY KEY,
	Fecha DATETIME NOT NULL,
	Dia TINYINT NOT NULL,
	Mes TINYINT NOT NULL,
	Anio SMALLINT NOT NULL,
	Trimestre TINYINT NOT NULL,
	DiaSemana TINYINT NOT NULL
);
GO